sudo: required

env:
  - MAVEN_VERSION=3.3.9

services:
  - docker

language: java
dist: trusty
jdk:
  - oraclejdk8

script:
  - mvn clean verify
  - mvn sonar:sonar -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_LOGIN
  - mvn install dockerfile:build;

before_install:
  - chmod +x .travis/main.sh
  - chmod +x mvnw
  - ./.travis/main.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker build -t $DOCKER_IMAGE .;
      docker push $DOCKER_IMAGE;
    fi

notifications:
  email:
      on_success: always # default: change
      on_failure: always # default: always
