server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: default
    service-url:
      defaultZone: http://localhost:8761
  server:
    waitTimeInMsWhenSyncEmpty: 5
